Fail a bug fix

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -17,20 +17,25 @@ jobs:
                     ${{ toJSON(github.event.pull_request.labels)  }}
                 EOF
 
-           # - name: Bug steps
+            - name: Failed deliberately
+              run: exit 2
 
-            - name: Take a nap
-              run: sleep 20
-            - name: Failed step
-              run: exit 1
-            - name: I will be skippped
-              run: echo I will print if previous steps succeed.
-            - name: I will execute
-              if: failure()
-              run: echo I will print if any previous step fails
-            - name: I will execute
-              if: ${{ failure() && job.status != 'cancelled' }}
-              run: echo I will always print, except when the workflow is cancelled.
-            - name: I will execute when cancelled
-              if: ${{ job.status == 'cancelled' }}
-              run: echo I will print if cancelled
+            - name: Bug step
+              if: failure() && contains(github.event.pull_request.title, 'fix')
+              run: echo I am a bug fix 
+
+#            - name: Take a nap
+#              run: sleep 20
+#            - name: Failed step
+#              run: exit 1
+#            - name: I will be skippped
+#              run: echo I will print if previous steps succeed.
+#            - name: I will execute
+#              if: failure()
+#              run: echo I will print if any previous step fails
+#            - name: I will execute
+#              if: ${{ failure() && job.status != 'cancelled' }}
+#              run: echo I will always print, except when the workflow is cancelled.
+#            - name: I will execute when cancelled
+#              if: ${{ job.status == 'cancelled' }}
+#              run: echo I will print if cancelled
